%endoflist
! IMP2021 Runtime Environment
! Copyright JD McMullin PhD, March 2021

! define the register numbers
%constinteger  r0=0,
               r1=1,
               r2=2,
               r3=3,
               r4=4,
               r5=5,
               r6=6,
               r7=7,
               r8=8,
               r9=9,
               r10=10,
               r11=11,
               r12=12,
               sp=13,
               fp=14,
               pc=15

%list
%endoffile
